#!/usr/bin/env python3

import subprocess
import sys


def sh(cmd, **args):
    code = subprocess.call(cmd.format(**args), shell=True)
    if code:
        exit(code)


argv = sys.argv[1:]

# Helper for rebuilding the docker image on demand
rebuild = False
if argv and argv[0] == '-r':
    rebuild = True
    argv = argv[1:]
elif subprocess.call('docker image inspect flategy 1> /dev/null', shell=True):
    rebuild = True
if rebuild:
    sh('./scripts/build_image')


sh('docker run --rm -it -v `pwd`:/work -w /work flategy'
   ' python3 scripts/run.py {command}',
   command=' '.join(argv))
