#!/usr/bin/env bash

BASE="$(dirname $(dirname $0))"
BUILD="${BASE}/build"
SRC="${BASE}/src"

CFLAGS_DEBUG="-O0 -g"
CFLAGS_RELEASE="-O3 -mtune=native"
CFLAGS_COMMON="-fpic -Wall -Wextra -Werror -std=c++14 -I ${BASE}/include -I/usr/include/python3.6m/ -I/usr/local/lib/python3.6/dist-packages/numpy/core/include/"

CFLAGS="${CFLAGS_DEBUG} ${CFLAGS_COMMON}"

mkdir -p ${BUILD}

g++ ${CFLAGS} ${SRC}/*.cpp -shared -o ${BUILD}/libflategy.so

if [[ ${1} == "test" ]]; then
    g++ ${CFLAGS} ${SRC}/test/*.cpp -o ${BUILD}/test -L${BUILD} -lflategy -lpython3.6m
    env LD_LIBRARY_PATH=${BUILD} ${BUILD}/test
fi
